package vsys

import "github.com/imajinyun/go-knifer/internal/system"

// Code generated by internal facade audit; DO NOT EDIT.

// NewGoInfo delegates to the internal system implementation.
func NewGoInfo() *GoInfo {
	return system.NewGoInfo()
}

// NewGoInfoWithOptions delegates to the internal system implementation.
func NewGoInfoWithOptions(opts ...GoInfoOption) *GoInfo {
	return system.NewGoInfoWithOptions(opts...)
}

// NewHostInfo delegates to the internal system implementation.
func NewHostInfo() *HostInfo {
	return system.NewHostInfo()
}

// NewOsInfo delegates to the internal system implementation.
func NewOsInfo() *OsInfo {
	return system.NewOsInfo()
}

// NewOsInfoWithOptions delegates to the internal system implementation.
func NewOsInfoWithOptions(opts ...OsInfoOption) *OsInfo {
	return system.NewOsInfoWithOptions(opts...)
}

// NewRuntimeInfo delegates to the internal system implementation.
func NewRuntimeInfo() *RuntimeInfo {
	return system.NewRuntimeInfo()
}

// GetHostInfo delegates to the internal system implementation.
func GetHostInfo() *HostInfo {
	return system.GetHostInfo()
}

// GetOsInfo delegates to the internal system implementation.
func GetOsInfo() *OsInfo {
	return system.GetOsInfo()
}

// GetUserInfo delegates to the internal system implementation.
func GetUserInfo() *UserInfo {
	return system.GetUserInfo()
}

// GetUserInfoWithOptions delegates to the internal system implementation.
func GetUserInfoWithOptions(opts ...UserInfoOption) *UserInfo {
	return system.GetUserInfoWithOptions(opts...)
}

// GetGoInfo delegates to the internal system implementation.
func GetGoInfo() *GoInfo {
	return system.GetGoInfo()
}

// GetRuntimeInfo delegates to the internal system implementation.
func GetRuntimeInfo() *RuntimeInfo {
	return system.GetRuntimeInfo()
}

// GetCurrentPID delegates to the internal system implementation.
func GetCurrentPID() int {
	return system.GetCurrentPID()
}

// GetTotalMemory delegates to the internal system implementation.
func GetTotalMemory() uint64 {
	return system.GetTotalMemory()
}

// GetFreeMemory delegates to the internal system implementation.
func GetFreeMemory() uint64 {
	return system.GetFreeMemory()
}

// GetMaxMemory delegates to the internal system implementation.
func GetMaxMemory() uint64 {
	return system.GetMaxMemory()
}

// GetTotalThreadCount delegates to the internal system implementation.
func GetTotalThreadCount() int {
	return system.GetTotalThreadCount()
}

// Get delegates to the internal system implementation.
func Get(key string, quiet bool) string {
	return system.Get(key, quiet)
}

// GetOrDefault delegates to the internal system implementation.
func GetOrDefault(key, def string) string {
	return system.GetOrDefault(key, def)
}

// GetInt delegates to the internal system implementation.
func GetInt(key string, def int) int {
	return system.GetInt(key, def)
}

// GetBool delegates to the internal system implementation.
func GetBool(key string, def bool) bool {
	return system.GetBool(key, def)
}

// NewUserInfo delegates to the internal system implementation.
func NewUserInfo() *UserInfo {
	return system.NewUserInfo()
}

// NewUserInfoWithOptions delegates to the internal system implementation.
func NewUserInfoWithOptions(opts ...UserInfoOption) *UserInfo {
	return system.NewUserInfoWithOptions(opts...)
}
