package vcron

import cronimpl "github.com/imajinyun/knifer-go/internal/cron"

// Code generated by internal facade audit; DO NOT EDIT.

// NewConfig delegates to the internal cron implementation.
func NewConfig() *Config {
	return cronimpl.NewConfig()
}

// NewCronError delegates to the internal cron implementation.
func NewCronError(format string, args ...any) *CronError {
	return cronimpl.NewCronError(format, args...)
}

// WrapCronError delegates to the internal cron implementation.
func WrapCronError(cause error, format string, args ...any) *CronError {
	return cronimpl.WrapCronError(cause, format, args...)
}

// NewPattern delegates to the internal cron implementation.
func NewPattern(expr string) (*Pattern, error) {
	return cronimpl.NewPattern(expr)
}

// MustNewPattern delegates to the internal cron implementation.
func MustNewPattern(expr string) *Pattern {
	return cronimpl.MustNewPattern(expr)
}

// NewCronTask delegates to the internal cron implementation.
func NewCronTask(id string, pattern *Pattern, task Task) *CronTask {
	return cronimpl.NewCronTask(id, pattern, task)
}

// NewTaskTable delegates to the internal cron implementation.
func NewTaskTable() *TaskTable {
	return cronimpl.NewTaskTable()
}
