package vimg

import "github.com/imajinyun/knifer-go/internal/imgx"

// Code generated by internal facade audit; DO NOT EDIT.

// VerifyIgnoreCase delegates to the internal imgx implementation.
func VerifyIgnoreCase(code, input string) bool {
	return imgx.VerifyIgnoreCase(code, input)
}

// NewMathGeneratorWith delegates to the internal imgx implementation.
func NewMathGeneratorWith(numberLength int, resultHasNegativeNumber bool) *MathGenerator {
	return imgx.NewMathGeneratorWith(numberLength, resultHasNegativeNumber)
}
