package vblf

import bloomfilter "github.com/imajinyun/knifer-go/internal/bloomfilter"

// Code generated by internal facade audit; DO NOT EDIT.

// NewIntMap delegates to the internal bloomfilter implementation.
func NewIntMap(size int) *IntMap {
	return bloomfilter.NewIntMap(size)
}

// NewLongMap delegates to the internal bloomfilter implementation.
func NewLongMap(size int) *LongMap {
	return bloomfilter.NewLongMap(size)
}

// NewFuncFilterWithMachineNum delegates to the internal bloomfilter implementation.
func NewFuncFilterWithMachineNum(maxValue int64, machineNum int, hashFunc HashFunc) *FuncFilter {
	return bloomfilter.NewFuncFilterWithMachineNum(maxValue, machineNum, hashFunc)
}

// NewFuncFilterWithMachineNumE delegates to the internal bloomfilter implementation.
func NewFuncFilterWithMachineNumE(maxValue int64, machineNum int, hashFunc HashFunc) (*FuncFilter, error) {
	return bloomfilter.NewFuncFilterWithMachineNumE(maxValue, machineNum, hashFunc)
}

// NewDefaultFilter delegates to the internal bloomfilter implementation.
func NewDefaultFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewDefaultFilter(maxValue)
}

// NewELFFilter delegates to the internal bloomfilter implementation.
func NewELFFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewELFFilter(maxValue)
}

// NewFNVFilter delegates to the internal bloomfilter implementation.
func NewFNVFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewFNVFilter(maxValue)
}

// NewHfFilter delegates to the internal bloomfilter implementation.
func NewHfFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewHfFilter(maxValue)
}

// NewHfIpFilter delegates to the internal bloomfilter implementation.
func NewHfIpFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewHfIpFilter(maxValue)
}

// NewJSFilter delegates to the internal bloomfilter implementation.
func NewJSFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewJSFilter(maxValue)
}

// NewPJWFilter delegates to the internal bloomfilter implementation.
func NewPJWFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewPJWFilter(maxValue)
}

// NewRSFilter delegates to the internal bloomfilter implementation.
func NewRSFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewRSFilter(maxValue)
}

// NewSDBMFilter delegates to the internal bloomfilter implementation.
func NewSDBMFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewSDBMFilter(maxValue)
}

// NewTianlFilter delegates to the internal bloomfilter implementation.
func NewTianlFilter(maxValue int64) *FuncFilter {
	return bloomfilter.NewTianlFilter(maxValue)
}

// RsHash delegates to the internal bloomfilter implementation.
func RsHash(str string) int32 {
	return bloomfilter.RsHash(str)
}

// JsHash delegates to the internal bloomfilter implementation.
func JsHash(str string) int32 {
	return bloomfilter.JsHash(str)
}

// PjwHash delegates to the internal bloomfilter implementation.
func PjwHash(str string) int32 {
	return bloomfilter.PjwHash(str)
}

// ElfHash delegates to the internal bloomfilter implementation.
func ElfHash(str string) int32 {
	return bloomfilter.ElfHash(str)
}

// BkdrHash delegates to the internal bloomfilter implementation.
func BkdrHash(str string) int32 {
	return bloomfilter.BkdrHash(str)
}

// SdbmHash delegates to the internal bloomfilter implementation.
func SdbmHash(str string) int32 {
	return bloomfilter.SdbmHash(str)
}

// DjbHash delegates to the internal bloomfilter implementation.
func DjbHash(str string) int32 {
	return bloomfilter.DjbHash(str)
}

// ApHash delegates to the internal bloomfilter implementation.
func ApHash(str string) int32 {
	return bloomfilter.ApHash(str)
}

// FnvHashString delegates to the internal bloomfilter implementation.
func FnvHashString(data string) int32 {
	return bloomfilter.FnvHashString(data)
}

// HfHash delegates to the internal bloomfilter implementation.
func HfHash(data string) int64 {
	return bloomfilter.HfHash(data)
}

// HfIpHash delegates to the internal bloomfilter implementation.
func HfIpHash(data string) int64 {
	return bloomfilter.HfIpHash(data)
}

// TianlHash delegates to the internal bloomfilter implementation.
func TianlHash(str string) int64 {
	return bloomfilter.TianlHash(str)
}

// JavaDefaultHash delegates to the internal bloomfilter implementation.
func JavaDefaultHash(str string) int32 {
	return bloomfilter.JavaDefaultHash(str)
}
