package vlog

import logx "github.com/imajinyun/knifer-go/internal/log"

// Code generated by internal facade audit; DO NOT EDIT.

// SetColorFactory delegates to the internal logx implementation.
func SetColorFactory(f ColorFactory) {
	logx.SetColorFactory(f)
}

// SetConsoleLevel delegates to the internal logx implementation.
func SetConsoleLevel(level Level) {
	logx.SetConsoleLevel(level)
}

// GetConsoleLevel delegates to the internal logx implementation.
func GetConsoleLevel() Level {
	return logx.GetConsoleLevel()
}

// SetFactory delegates to the internal logx implementation.
func SetFactory(factory LogFactory) {
	logx.SetFactory(factory)
}

// GetFactory delegates to the internal logx implementation.
func GetFactory() LogFactory {
	return logx.GetFactory()
}

// Get delegates to the internal logx implementation.
func Get(name string) Log {
	return logx.Get(name)
}

// GetWithOptions delegates to the internal logx implementation.
func GetWithOptions(name string, opts ...LoggerOption) Log {
	return logx.GetWithOptions(name, opts...)
}

// GetDefault delegates to the internal logx implementation.
func GetDefault() Log {
	return logx.GetDefault()
}

// GetDefaultWithOptions delegates to the internal logx implementation.
func GetDefaultWithOptions(opts ...LoggerOption) Log {
	return logx.GetDefaultWithOptions(opts...)
}
