package vskt

import (
	"bytes"
	"net"
	"time"

	socketx "github.com/imajinyun/go-knifer/internal/socket"
)

// Code generated by internal facade audit; DO NOT EDIT.

// NewAioClientWithConn delegates to the internal socketx implementation.
func NewAioClientWithConn(conn net.Conn, action IoAction[*bytes.Buffer], cfg *SocketConfig) *AioClient {
	return socketx.NewAioClientWithConn(conn, action, cfg)
}

// ChannelUtilDial delegates to the internal socketx implementation.
func ChannelUtilDial(addr *net.TCPAddr, timeout time.Duration) (net.Conn, error) {
	return socketx.ChannelUtilDial(addr, timeout)
}

// NewSocketError delegates to the internal socketx implementation.
func NewSocketError(err error) *SocketRuntimeError {
	return socketx.NewSocketError(err)
}

// NewSocketErrorMsg delegates to the internal socketx implementation.
func NewSocketErrorMsg(msg string) *SocketRuntimeError {
	return socketx.NewSocketErrorMsg(msg)
}

// NewSocketErrorf delegates to the internal socketx implementation.
func NewSocketErrorf(format string, args ...any) *SocketRuntimeError {
	return socketx.NewSocketErrorf(format, args...)
}

// WrapSocketError delegates to the internal socketx implementation.
func WrapSocketError(err error, msg string) *SocketRuntimeError {
	return socketx.WrapSocketError(err, msg)
}

// GetRemoteAddress delegates to the internal socketx implementation.
func GetRemoteAddress(conn net.Conn) net.Addr {
	return socketx.GetRemoteAddress(conn)
}
