package vcache

import (
	"time"

	cache "github.com/imajinyun/go-knifer/internal/cache"
)

// Code generated by internal facade audit; DO NOT EDIT.

// NewFIFOCache delegates to the internal cache implementation.
//
// Deprecated: use NewFIFO.
func NewFIFOCache[K comparable, V any](capacity int) *FIFOCache[K, V] {
	return NewFIFOWithOptions[K, V](WithCapacity[K, V](capacity))
}

// NewFIFOCacheWithTimeout delegates to the internal cache implementation.
//
// Deprecated: use NewFIFOWithTimeout.
func NewFIFOCacheWithTimeout[K comparable, V any](capacity int, timeout time.Duration) *FIFOCache[K, V] {
	return NewFIFOWithOptions[K, V](WithCapacity[K, V](capacity), WithTimeout[K, V](timeout))
}

// NewLFUCache delegates to the internal cache implementation.
//
// Deprecated: use NewLFU.
func NewLFUCache[K comparable, V any](capacity int) *LFUCache[K, V] {
	return NewLFUWithOptions[K, V](WithCapacity[K, V](capacity))
}

// NewLFUCacheWithTimeout delegates to the internal cache implementation.
//
// Deprecated: use NewLFUWithTimeout.
func NewLFUCacheWithTimeout[K comparable, V any](capacity int, timeout time.Duration) *LFUCache[K, V] {
	return NewLFUWithOptions[K, V](WithCapacity[K, V](capacity), WithTimeout[K, V](timeout))
}

// NewLRUCache delegates to the internal cache implementation.
//
// Deprecated: use NewLRU.
func NewLRUCache[K comparable, V any](capacity int) *LRUCache[K, V] {
	return NewLRUWithOptions[K, V](WithCapacity[K, V](capacity))
}

// NewLRUCacheWithTimeout delegates to the internal cache implementation.
//
// Deprecated: use NewLRUWithTimeout.
func NewLRUCacheWithTimeout[K comparable, V any](capacity int, timeout time.Duration) *LRUCache[K, V] {
	return NewLRUWithOptions[K, V](WithCapacity[K, V](capacity), WithTimeout[K, V](timeout))
}

// NewTimedCache delegates to the internal cache implementation.
//
// Deprecated: use NewTimed.
func NewTimedCache[K comparable, V any](timeout time.Duration) *TimedCache[K, V] {
	return NewTimedWithOptions[K, V](WithTimeout[K, V](timeout))
}

// NewNo delegates to the internal cache implementation.
func NewNo[K comparable, V any]() *NoCache[K, V] {
	return &NoCache[K, V]{NoCache: cache.NewNo[K, V]()}
}

// NewWeakCache delegates to the internal cache implementation.
//
// Deprecated: use NewWeak.
func NewWeakCache[K comparable, V any](timeout time.Duration) *WeakCache[K, V] {
	return NewWeakWithOptions[K, V](WithTimeout[K, *V](timeout))
}
