package vcache

import cache "github.com/imajinyun/knifer-go/internal/cache"

// Code generated by internal facade audit; DO NOT EDIT.

// NewNo delegates to the internal cache implementation.
func NewNo[K comparable, V any]() *NoCache[K, V] {
	return &NoCache[K, V]{NoCache: cache.NewNo[K, V]()}
}
