package vhttp

import (
	"net/http"
	"time"

	httpx "github.com/imajinyun/go-knifer/internal/http"
)

// Code generated by internal facade audit; DO NOT EDIT.

// BuildContentType delegates to the internal httpx implementation.
func BuildContentType(contentType, charset string) string {
	return httpx.BuildContentType(contentType, charset)
}

// IsDefaultContentType delegates to the internal httpx implementation.
func IsDefaultContentType(contentType string) bool {
	return httpx.IsDefaultContentType(contentType)
}

// IsFormURLEncoded delegates to the internal httpx implementation.
func IsFormURLEncoded(contentType string) bool {
	return httpx.IsFormURLEncoded(contentType)
}

// GuessContentType delegates to the internal httpx implementation.
func GuessContentType(body string) ContentType {
	return httpx.GuessContentType(body)
}

// SetCookieJar delegates to the internal httpx implementation.
func SetCookieJar(jar http.CookieJar) {
	httpx.SetCookieJar(jar)
}

// GetCookieJar delegates to the internal httpx implementation.
func GetCookieJar() http.CookieJar {
	return httpx.GetCookieJar()
}

// CloseCookie delegates to the internal httpx implementation.
func CloseCookie() {
	httpx.CloseCookie()
}

// NewError delegates to the internal httpx implementation.
func NewError(msg string, cause error) *Error {
	return httpx.NewHTTPError(msg, cause)
}

// Errorf delegates to the internal httpx implementation.
func Errorf(format string, args ...any) *Error {
	return httpx.HTTPErrorf(format, args...)
}

// SetGlobalMaxRedirects delegates to the internal httpx implementation.
func SetGlobalMaxRedirects(n int) {
	httpx.SetGlobalMaxRedirects(n)
}

// GetGlobalMaxRedirects delegates to the internal httpx implementation.
func GetGlobalMaxRedirects() int {
	return httpx.GetGlobalMaxRedirects()
}

// SetGlobalFollowRedirects delegates to the internal httpx implementation.
func SetGlobalFollowRedirects(b bool) {
	httpx.SetGlobalFollowRedirects(b)
}

// GetGlobalFollowRedirects delegates to the internal httpx implementation.
func GetGlobalFollowRedirects() bool {
	return httpx.GetGlobalFollowRedirects()
}

// SetGlobalUserAgent delegates to the internal httpx implementation.
func SetGlobalUserAgent(ua string) {
	httpx.SetGlobalUserAgent(ua)
}

// GetGlobalUserAgent delegates to the internal httpx implementation.
func GetGlobalUserAgent() string {
	return httpx.GetGlobalUserAgent()
}

// SetIgnoreEOFError delegates to the internal httpx implementation.
func SetIgnoreEOFError(b bool) {
	httpx.SetIgnoreEOFError(b)
}

// IsIgnoreEOFError delegates to the internal httpx implementation.
func IsIgnoreEOFError() bool {
	return httpx.IsIgnoreEOFError()
}

// SetTrustAnyHost delegates to the internal httpx implementation.
func SetTrustAnyHost(b bool) {
	httpx.SetTrustAnyHost(b)
}

// IsTrustAnyHost delegates to the internal httpx implementation.
func IsTrustAnyHost() bool {
	return httpx.IsTrustAnyHost()
}

// SetGlobalBoundary delegates to the internal httpx implementation.
func SetGlobalBoundary(b string) {
	httpx.SetGlobalBoundary(b)
}

// GetGlobalBoundary delegates to the internal httpx implementation.
func GetGlobalBoundary() string {
	return httpx.GetGlobalBoundary()
}

// SetGlobalDecodeURL delegates to the internal httpx implementation.
func SetGlobalDecodeURL(b bool) {
	httpx.SetGlobalDecodeURL(b)
}

// IsGlobalDecodeURL delegates to the internal httpx implementation.
func IsGlobalDecodeURL() bool {
	return httpx.IsGlobalDecodeURL()
}

// HTMLEscape delegates to the internal httpx implementation.
func HTMLEscape(s string) string {
	return httpx.HTMLEscape(s)
}

// HTMLUnescape delegates to the internal httpx implementation.
func HTMLUnescape(s string) string {
	return httpx.HTMLUnescape(s)
}

// CleanHTML delegates to the internal httpx implementation.
func CleanHTML(s string) string {
	return httpx.CleanHTML(s)
}

// FilterHTMLTag delegates to the internal httpx implementation.
func FilterHTMLTag(s string, tagNames ...string) string {
	return httpx.FilterHTMLTag(s, tagNames...)
}

// Options delegates to the internal httpx implementation.
func Options(rawURL string) *Request {
	return httpx.Options(rawURL)
}

// NewSimpleServerAddr delegates to the internal httpx implementation.
func NewSimpleServerAddr(addr string) *SimpleServer {
	return httpx.NewSimpleServerAddr(addr)
}

// CreateServer delegates to the internal httpx implementation.
func CreateServer(port int) *SimpleServer {
	return httpx.CreateServer(port)
}

// IsRedirected delegates to the internal httpx implementation.
func IsRedirected(status int) bool {
	return httpx.IsRedirected(status)
}

// IsHTTPS delegates to the internal httpx implementation.
func IsHTTPS(u string) bool {
	return httpx.IsHTTPS(u)
}

// IsHTTP delegates to the internal httpx implementation.
func IsHTTP(u string) bool {
	return httpx.IsHTTP(u)
}

// CreateRequest delegates to the internal httpx implementation.
func CreateRequest(method Method, rawURL string) *Request {
	return httpx.CreateRequest(method, rawURL)
}

// CreateGet delegates to the internal httpx implementation.
func CreateGet(rawURL string, followRedirects bool) *Request {
	return httpx.CreateGet(rawURL, followRedirects)
}

// CreatePost delegates to the internal httpx implementation.
func CreatePost(rawURL string) *Request {
	return httpx.CreatePost(rawURL)
}

// GetWithTimeout delegates to the internal httpx implementation.
func GetWithTimeout(rawURL string, timeout time.Duration) string {
	return httpx.GetWithTimeout(rawURL, timeout)
}

// GetWithParams delegates to the internal httpx implementation.
func GetWithParams(rawURL string, params map[string]any) string {
	return httpx.GetWithParams(rawURL, params)
}

// PostString delegates to the internal httpx implementation.
func PostString(rawURL, body string) string {
	return httpx.PostString(rawURL, body)
}

// DownloadString delegates to the internal httpx implementation.
func DownloadString(rawURL, customCharset string) string {
	return httpx.DownloadString(rawURL, customCharset)
}

// DownloadBytes delegates to the internal httpx implementation.
func DownloadBytes(rawURL string) []byte {
	return httpx.DownloadBytes(rawURL)
}

// EncodeParams delegates to the internal httpx implementation.
func EncodeParams(rawURL string) string {
	return httpx.EncodeParams(rawURL)
}

// DecodeParamMap delegates to the internal httpx implementation.
func DecodeParamMap(paramsStr string) map[string]string {
	return httpx.DecodeParamMap(paramsStr)
}

// DecodeParams delegates to the internal httpx implementation.
func DecodeParams(paramsStr string) map[string][]string {
	return httpx.DecodeParams(paramsStr)
}

// URLWithForm delegates to the internal httpx implementation.
func URLWithForm(rawURL string, form map[string]any) string {
	return httpx.URLWithForm(rawURL, form)
}

// GetCharsetFromContentType delegates to the internal httpx implementation.
func GetCharsetFromContentType(ct string) string {
	return httpx.GetCharsetFromContentType(ct)
}

// GetCharsetFromHTML delegates to the internal httpx implementation.
func GetCharsetFromHTML(html string) string {
	return httpx.GetCharsetFromHTML(html)
}

// GetMimeType delegates to the internal httpx implementation.
func GetMimeType(filename string) string {
	return httpx.GetMimeType(filename)
}
